name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Make sure this matches your Cypress compatible Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run specific Cypress test
        run: npm run test:login
       
