name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress version
        run: npx cypress --version

      - name: List Cypress tests
        run: ls cypress/e2e/tests/

      - name: Run specific Cypress test
        run: npx cypress run --spec "cypress/e2e/tests/loginTest.cy.js"
