name: Sanity End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Match your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:login
